name: movies_app
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 1.0.4
  http: 0.13.4
  equatable: 2.0.3
  cached_network_image: 3.2.1
  email_validator: 2.0.1
  firebase_auth: 3.4.1
  google_sign_in: ^5.4.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
